### ISSUE TITLE
Fall sounds not working

### ISSUE THREAD

**Issue by codergautam** [ViaVersion/ViaRewind-Legacy-Support#13]
if i go on 1.8 and i like jump or fall the fall sound doesnt play

**Comment by PierreSchwang** [comment]
Can't reproduce using latest VR-Legacy-Support

**Comment by Jo0001** [comment]
Make sure you have latest the CI builds
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.0.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.0.2-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-2.0.2-SNAPSHOT.jar
ViaRewind Legacy Support (Bukkit) - https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/lastSuccessfulBuild/artifact/target/viarewind-legacy-support-1.4.1.jar

**Comment by codergautam** [comment]
Thanks so much.
