### ISSUE TITLE
1.7 Carpet Rubberband

### ISSUE THREAD

**Issue by ItsVinnyX** [ViaVersion/ViaRewind-Legacy-Support#27]
1.14.4 Server with ViaVersion, ViaRewind, ViaBackwards, ViaRewind-Legacy, ProtocolLib, and custom plugins.

1.7 Players rubberband when they hit carpets. They have to jump over the block in order to move past it.

**Comment by ItsVops** [comment]
Would there be any way to disable carpets pushing players up on versions other then 1.7?
