### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Thefluffypvper1** [ViaVersion/ViaRewind-Legacy-Support#33]
My server is 1.8.8 and i logged onto it with a  1.16.5 client and got spammed this console error.
https://paste.helpch.at/denalelobo.shell

**Comment by Jo0001** [comment]
That looks like a ViaVersion error. Please open a new issue here https://github.com/ViaVersion/ViaVersion/issues/new?assignees=&labels=Unconfirmed&template=bug_report.yml
