### ISSUE TITLE
Probably not supporting 1.18? I'm not really sure...

### ISSUE THREAD

**Issue by Zen-kun04** [ViaVersion/ViaRewind-Legacy-Support#43]
So basically I'm running a Spigot 1.18.2 server and when using ViaRewind Legacy Support ladders still bugging all the time, like I can't climb them.

Any solution?

**Comment by Jo0001** [comment]
Make sure you use the latest version from https://ci.viaversion.com/view/All/job/ViaRewind%20Legacy%20Support/lastSuccessfulBuild/artifact/target/viarewind-legacy-support-1.4.2-SNAPSHOT.jar
