### ISSUE TITLE
Console error when placing blocks on 1.19.3 server

### ISSUE THREAD

**Issue by Jo0001** [ViaVersion/ViaRewind-Legacy-Support#56]
## `/viaversion dump` Output
https://dump.viaversion.com/fd15227796ed08bd3d16e62550dea8c1faa187c85f7f6622f584c3461305cbc2

## Console Error
https://paste.gg/p/anonymous/602257cfb5d04d3a9ab69f7632c39ac7

## Bug Description
The console is spammed with VRLS erros when placing blocks

## Steps to Reproduce
1. Create a 1.19.3 server
2. Login with 1.8.8
3. Place a block
4. Error appears in console

## Expected Behavior
No console errors

## Additional Server Info
Latest paper and Via*

**Comment by ARDragssss** [comment]
is this fixed yet?

**Comment by Jo0001** [comment]
No but we'll post an update here when its fixed
