### ISSUE TITLE
ViaRewind-Legacy-Support loading issue

### ISSUE THREAD

**Issue by ZeyKoYT9955** [ViaVersion/ViaRewind-Legacy-Support#58]
On an brend new 1.12.2 paper spigot version with lasted Viaversion (4.6.2) Lasted ViaRewind (2.0.3) and lasted ViaBackWards (4.6.1) and lasted ViaRewind Legagcy ( 1.4.2) , when start the server it send this error:
[latest.log](https://github.com/ViaVersion/ViaRewind-Legacy-Support/files/11004536/latest.log)

**Comment by TheJoshue** [comment]
I confirm this happens even with latest versions of the date and time i am writing this message.
![image](https://github.com/ViaVersion/ViaRewind-Legacy-Support/assets/56804505/76695ee3-1cba-4ec6-95a4-0de5704d3cad)

**Comment by FlorianMichael** [comment]
Fixed in latest master commit
