### ISSUE TITLE
Server crashed error

### ISSUE THREAD

**Issue by qaz197418i** [ViaVersion/ViaRewind-Legacy-Support#67]
### `/viaversion dump` Output

https://dump.viaversion.com/8147c6c81236f736bda3a114a8534cf5fed0016373ba312efc2c8d4595a6f66b

### Console Error

```
https://pastebin.com/PjErZa6u
```

### Bug Description

My server is PaperSpigot 1.12.2. When my server is running, if I use players with version 1.8.9, it will cause the server to crash. I am not sure what operation caused the crash because it happens suddenly every time

### Steps to Reproduce

To be honest, I don't know how to reproduce this error, but my personal guess is to place blocks

### Expected Behavior

1.8 The client can play normally without causing server crashes

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

**Comment by FlorianMichael** [comment]
Fixed in latest master commit
