### ISSUE TITLE
Ladders and Lily Pads Still not working

### ISSUE THREAD

**Issue by DetahMC** [ViaVersion/ViaRewind-Legacy-Support#69]
- Running 1.20.2
- have had this issue since 1.19
- yes, config has been modified
- protocollib is active and working
- can't see any errors in console

Attached, please find console startup.

https://gist.github.com/GGServersAutoPaste/35f127fc420a998dcc3f5c70c7f32645

**Comment by DetahMC** [comment]
Tried using snapshot version. Did not work. 

https://gist.github.com/GGServersAutoPaste/f8bcb70465b045f534cecd39d2bc96c3

**Comment by editid0** [comment]
I'm having the same issue on a 1.20.4 paper server, 1.8.9 client goes all buggy on ladders and lilypads. No errors in console either.

**Comment by Kichura** [comment]
> I'm having the same issue on a 1.20.4 paper server, 1.8.9 client goes all buggy on ladders and lilypads. No errors in console either.

Made #76 because of that although has turned out to be a paper-specific problem that needs to be fixed upon tomorrow.
