### ISSUE TITLE
Plugin is spamming NoSuchMethod errors in console

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaRewind-Legacy-Support#73]
When starting up the server with this plugin active - The console starts spamming the same NoSuchMethod error over and over again.
Console logs can be found [here](https://pastebin.com/raw/s7KT0STa). *(I Ctrl-C'd this because it would've just continued endlessly)*

I may assume that one day, This plugin will be merged into ViaRewind itself as seperating the fixes into bukkit only is just unnecessary.

**Comment by FlorianMichael** [comment]
Latest ViaRewind Legacy Support only works with dev versions of Via because for some reason we did the protocol version rewrite in dev.
