### ISSUE TITLE
1.7 - 1.8.9 players cannot climb ladders regardless of fix option being enabled

### ISSUE THREAD

**Issue by Kichura** [ViaVersion/ViaRewind-Legacy-Support#76]
When starting a new world in Paper 1.20.4 and using the latest CI builds of via*, Attempting to climb ladders causes player to lagback and end up where they were standing previously before the climbing has started, This however does not happen when playing on 1.9.x instead.

The ViaVersion dump can be found [here](https://dump.viaversion.com/c8b3b2dedac469b5585103ee3683ee2c62eb4222076bc5235661f99cb9bc1bce) and the console logs can be found [here](https://mclo.gs/MqgD1xy).

**Comment by FlorianMichael** [comment]
Does this happen on a Spigot server?

**Comment by Kichura** [comment]
Doesn't seem to apply on spigot, guessing paper somehow broke it.

**Comment by FlorianMichael** [comment]
https://github.com/ViaVersion/ViaRewind-Legacy-Support/commit/3cc472e4ae3dd3cebe3ddf5a4daf6ccf383312fc
